# Create Foundational Use Case Structure
mkdir '00. Disabled'
mkdir '01. Development'
mkdir '02. System'
mkdir '03. Production'
mkdir '04. Apps'

# Implement SPEED Use Case Framework Structure
mkdir '03. Production/00. Self-Monitoring'
mkdir '03. Production/01. Access Control'
mkdir '03. Production/02. Application'
mkdir '03. Production/03. Host'
mkdir '03. Production/04. Mobile'
mkdir '03. Production/05. Wireless Network'
mkdir '03. Production/06. Internal Network'
mkdir '03. Production/07. Cloud'
mkdir '03. Production/08. Perimeter'
mkdir '03. Production/09. Physical'
mkdir '03. Production/10. Policy'
mkdir '03. Production/11. Attack Patterns'
mkdir '03. Production/11. Attack Patterns/a. Insider Threat'
mkdir '03. Production/11. Attack Patterns/b. Script Kiddie'
mkdir '03. Production/11. Attack Patterns/c. Cyber Criminal'
mkdir '03. Production/11. Attack Patterns/d. Nation State'
mkdir '03. Production/12. Threat Intelligence'
mkdir '03. Production/12. Threat Intelligence/a. Commoditized Threat Intelligence'
mkdir '03. Production/12. Threat Intelligence/b. Regional Threat Intelligence'
mkdir '03. Production/12. Threat Intelligence/c. Industry Threat Intelligence'
mkdir '03. Production/12. Threat Intelligence/d. Tailored Threat Intelligence'
mkdir '03. Production/13. Threat Modelling'
mkdir '03. Production/13. Threat Modelling/a. Attacker Profile name #1'
mkdir '03. Production/13. Threat Modelling/a. Attacker Profile name #1/i. Attack Campaign A'
mkdir '03. Production/13. Threat Modelling/a. Attacker Profile name #1/ii. Attack Campaign B'
mkdir '03. Production/13. Threat Modelling/a. Attacker Profile name #1/iii. Attack Campaign C'
mkdir '03. Production/13. Threat Modelling/b. Attacker Profile name #2'
mkdir '03. Production/13. Threat Modelling/b. Attacker Profile name #2/i. Attack Campaign A'
mkdir '03. Production/13. Threat Modelling/b. Attacker Profile name #2/ii. Attack Campaign B'
mkdir '03. Production/13. Threat Modelling/b. Attacker Profile name #2/iii. Attack Campaign C'
mkdir '03. Production/13. Threat Modelling/c. Attacker Profile name #3'
mkdir '03. Production/13. Threat Modelling/c. Attacker Profile name #3/i. Attack Campaign A'
mkdir '03. Production/13. Threat Modelling/c. Attacker Profile name #3/ii. Attack Campaign B'
mkdir '03. Production/13. Threat Modelling/c. Attacker Profile name #3/iii. Attack Campaign C'

